blank_issues_enabled: false
contact_links:
  - name: Ask a question / general discussion
    url: https://github.com/evolve-ops/evolve/discussions
    about: Not sure if it's a bug? Have a setup question? Start here.
